### ISSUE TITLE
discontinued/example code ff7_ammo, _weapons, _units

### ISSUE THREAD

**Issue by csathdfw** [FoxForce7/Modset#12]
I would like to move
ff7_ammo
ff7_weapons
ff7_units
out of this repo into a sub folder or something. 
- ff7_units is spartas thing and needs a rework to account for current modset. 
- ff7_ammo and _weapons will lend portions of code for the ff7_compat_ace (9mm, .45acp, .300blk) in the near future. but both those can serve as example code too, as some of the contents is dormant (or commented) code which should still work if uncommented, allthough having those portions working as is was decided to be unneccesary (aka bradley-gun, flechette lmg)

**Comment by Vadric** [comment]
agree, i think new repo for optionals and examples

**Comment by Vadric** [comment]
weapons/ammo removed from main branch, units made functional ready to be put in
