### ISSUE TITLE
Possible OPT in of ACE menu expanded?

### ISSUE THREAD

**Issue by HeliumxU** [FoxForce7/Modset#15]
An Issue I have with arma's built in scroll menu is that it doesn't work well when we have the quite elegant and easy to use ACE menu. I'm no server guy though, so I don't even know if we could have it as an optional mod, just thought I'd link it.
http://steamcommunity.com/sharedfiles/filedetails/?id=1376867375

**Comment by Vadric** [comment]
this looks interesting

**Comment by Gunslinger2102** [comment]
Seems a bit bad, specially if it does remove the scroll menu (which it appears it does) which will make it alot harder to fly specially if you're using mouse for fine tuning the angle that you're on to avoid something

**Comment by HeliumxU** [comment]
As an infantry man I'd love this, and your issue is kinda why I asked if we could make it an optional thing, as it seems mostly client side?

(Also kierran isn't it easier to alt than to scroll when locking your view for a fine adjustment?)

**Comment by Gunslinger2102** [comment]
The ACE Menu makes it so you have to choose to either use it or Use alt to go through it so either way you'd have no mouse control at all when flying where as with the scroll menu you can keep all control of the aircraft, but if it's an optional mod then we'd need to have it separate from the actual modpack which could be a bit annoying for those that do want to use it
