### ISSUE TITLE
Possible trimming of RUS Forces? (800mb)

### ISSUE THREAD

**Issue by HeliumxU** [FoxForce7/Modset#16]
https://steamcommunity.com/sharedfiles/filedetails/?id=543460260

Seems like it has alot of stuff but it could still be trimmed down, depending on how hard that would be?

give me my altyn/k6-3 please.

**Comment by Vadric** [comment]
A possible pack for Russian themed month, if you want to rip out that one helmet then go ahead, but probably not many missions it would be suitable for.
