### ISSUE TITLE
Ni Arms / HLC

### ISSUE THREAD

**Issue by Vadric** [FoxForce7/Modset#3]
[NI Arms pack.](https://forums.bohemia.net/forums/topic/190455-niarms-release-thread/)
Heres my votes on the stuff:
AR15 - Like it.
MP5 - Like it, edit Ammo.
Minimi - Like it, cut down on models, but vanilla is fine also.
ARC - Unsure.
G3 Unsure, requires custom ammo, mod or scrap?
FAL - Unsure, requires custom ammo, mod or scrap?
M60E4 - Only 2 models, want?
G36 Unsure, requires custom ammo, mod or scrap?
M14 - Vanilla m14 is better.
Springfield - Vanilla m14 is better.
MG3 - Never used, old.
Aug - No Aussies round here.
AWC - Never used, possible to pull single model.
AK - Vanilla AK's are better.
Minigun - lolwut?
Sig - Vanilla sig's enough.

AR15 pack is only one I actually want.

**Comment by PricelessFox** [comment]
AR15 - of course
MP5 - Yes
Minimi - Yes please - much more realistic model and sounds for 249esque weapon than vanilla..
ARC - is this the honey badger? Please keep!
G3 - i dont see any reason not to have it...its not cancer
FAL - one of my favourite weapons (cos SADF)
M60E4 - Only 2 models, want both! (We have so few LMG)
G36 - i love these variants..
M14 - Vanilla m14 is better, agreed
Springfield - Vanilla m14 is better, agreed
MG3 - NO
Aug - Im not against the Aug it would be cool to have but not 100 differnt variants.. Wouldnt mind an ironsight version and one with fixed scope
AWC - one of the nicest bolt action weapons, 7.62, please dont pull
AK - Vanilla AK's are better/we dont need 100 variants of ak
Minigun - NO
Sig - almost never used by most, wont be missed

**Comment by csathdfw** [comment]
* arc = acr 

honeybadger is in ar15 pack, the other .300blk too afaik

would keep partial (ar15, mp5, m249, g3, g36, atleast ), I can do ammo compat to use vanilla/ace/ff7 mags and ammo for (and hide, not delete) the exotic mags, for appropiate ammoshare and smaller lists in our arsenal

**Comment by Vadric** [comment]
M60E4 We have many LMG, both with vanilla and Mini pack contains all the 7.62 ones, mini pack has: 
"hlc_lmg_minimipara","hlc_lmg_minimi","hlc_lmg_m249para","hlc_lmg_M249E2","hlc_lmg_minimi_railed","hlc_m249_pip1","hlc_m249_SQuantoon","hlc_lmg_mk48","hlc_lmg_minimipara_30Rnd","hlc_lmg_minimipara_railed","hlc_lmg_minimipara_railed_30Rnd","hlc_lmg_minimipara_long","hlc_lmg_minimipara_long_30Rnd","hlc_lmg_minimipara_long_railed","hlc_lmg_minimipara_long_railed_30Rnd","hlc_lmg_minimi_30Rnd","hlc_lmg_minimi_railed_30Rnd","hlc_lmg_m249para_30Rnd","hlc_lmg_M249E2_30Rnd","hlc_lmg_M249E1","hlc_lmg_M249E1_30Rnd","hlc_m249_pip1_30Rnd","hlc_m249_pip2","hlc_m249_pip2_30Rnd","hlc_m249_pip3","hlc_m249_pip3_30Rnd","hlc_m249_pip4","hlc_m249_pip4_30Rnd","hlc_m249_SQuantoon_30Rnd","hlc_lmg_mk46","hlc_lmg_mk46mod1","hlc_lmg_mk48mod1",
on other hand its only another 2 models no big deal

**Comment by Gunslinger2102** [comment]
personally i'd like to have just the P226R(Elite, Equinox and Combat versions only 8 in total) from the Sig pistols, they were the only pistols i used on sandbox when we had the ability to change loadout especially since you could change the sight on them to something that was more comfortable to you with the options of having different iron sights to red dots on them, without them it's only the FNX-45 and P99 with effective killing potential per mag imo
i agree with price on pretty much everything else though
for the augs the Aug A3 has choices for both irons and actual sights, if i read correctly it's the Aug A2 that you also want that has the scope inbuilt on it

**Comment by csathdfw** [comment]
oh yea, +1 on the sig p226
