### ISSUE TITLE
Beards

### ISSUE THREAD

**Issue by Vadric** [FoxForce7/Modset#7]
Do we want this beard mod?

[Armaholic](http://www.armaholic.com/page.php?id=25411)

**Comment by PricelessFox** [comment]
Im not against the beards - i do like growing a moustache every now and then

**Comment by csathdfw** [comment]
-1 discard 
(would want proper beards, haircuts)

**Comment by Vadric** [comment]
Neutral, its small, but less is more.

**Comment by Vadric** [comment]
5/0 vote on discord,
