### ISSUE TITLE
Ivory Cars

### ISSUE THREAD

**Issue by Vadric** [FoxForce7/Modset#8]
Do we want Ivory Cars?

**Comment by PricelessFox** [comment]
What is its exact size?
As I recall its only around 200mb
I vote yes

**Comment by csathdfw** [comment]
+1 keep
(complete or partial)

**Comment by Vadric** [comment]
190e (old Mercedes)
Porch 911
Koenigsegg CCX
Bentley Continental Supersports
e36 (BMW)
Lotus Elise
erj135 (Jet Plane)
Evo (Mitsubishi)
F1
Dodge gt500
Golf GTI
Lexus ISF
Lexus LFA
Lambo 560
M3 BMW
McLaren mp4
Audi R8
Skyline R34
Audi rs4
Chevy Suburban
Toyota Supra
Bugatti Veyron
Subaru WRX
Lamborghini Reventon

**Comment by Vadric** [comment]
Im more for the normal looking cars and only a few of the super cars, but no big deal. Some of the paint jobs are real bad, limit? Also want to look into other car mods, by adding this we may get lazy about checking out the competition.

**Comment by csathdfw** [comment]
coming from roleplay arma, there is only ivory or jonzi cars. and jonzi sense of realism is fueltanks which last for very short and moonsled like acceleration, also with jonzi you get most steering wheels on the right (which is the wrong 😁 ) side. there is couple more cars out there, but most lack quality/are unfinished or are single cars with too many paintjobs

**Comment by Vadric** [comment]
ASN has some [new vehicles](https://armaservices.net/)
I like the [police cruisers](https://steamcommunity.com/sharedfiles/filedetails/?id=1289516088) and swat [vehicle](https://steamcommunity.com/sharedfiles/filedetails/?id=1303409827), but havent tried in game yet

Also this [pack](https://charlieco89mods.jimdo.com/en/) of red service vehicles, but maybe that medical dlc covered this, [fire truck](http://www.armaholic.com/page.php?id=32260) would be cool though.

Not a big deal for me, I request these ones:
190e (old Mercedes)
e36 (BMW)
Evo (Mitsubishi)
gt500
Golf GTI
M3 BMW
Skyline R34
Chevy Suburban
Subaru WRX

**Comment by csathdfw** [comment]
my desired minimum of ivory cars would be:

bmw m3 e92 **(2seats)**
subaru wrx **(4seats)**
shelby gt500 **(2seats)**
chevrolet suburban **(4-8seats?)** (incl porice version) 

personally Id like to see also:
mclaren mp4-12c **(2seats)** (too low rideheight most of normal road tho)
vw golf mk5 gti **(2-4seats?)** 
audi rs4 **(4seats)** (incl taxi version)
mitsubishi evoX **(4seats)**

**Comment by ashw** [comment]
Would much rather focus on arma engines strengths and immersion, the supercars suck for both. Chevy suburban sounds like a decent idea. I am much more for keeping things lightweight in terms of code running and memory usage. I am not against terrains as they are only loaded one at a time.

**Comment by Vadric** [comment]
yeah i guess i change my mind and only care for the suburban

**Comment by Vadric** [comment]
some cars will go in, if any mroe cars are requested/hated, reopen
